FROM node:14-alpine as builder

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json ./
COPY package-lock.json ./

RUN apk --no-cache add git
RUN npm install

COPY . .

RUN apk update && apk add bash

# # add app
# COPY . .
RUN npm run build

#build for production
FROM nginx:alpine
COPY --from=builder  /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
